/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pe.edu.unmsm.software.eapisw.controller;

/**
 *
 * @author Purple
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setExtendedState(Main.MAXIMIZED_BOTH);
        this.setTitle("Biconik - Sistema de Almacén");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        ventasMenu = new javax.swing.JMenu();
        editMenu = new javax.swing.JMenu();
        productEditItem = new javax.swing.JMenuItem();
        workerEditItem = new javax.swing.JMenuItem();
        consultMenu = new javax.swing.JMenu();
        consultClientItem = new javax.swing.JMenuItem();
        configMenu = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        btnSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desktopPane.setBackground(new java.awt.Color(0, 199, 154));

        ventasMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/edu/unmsm/software/eapisw/controller/files/icons/icons8-computer-30.png"))); // NOI18N
        ventasMenu.setMnemonic('f');
        ventasMenu.setText("Ventas");
        ventasMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ventasMenuMouseClicked(evt);
            }
        });
        menuBar.add(ventasMenu);

        editMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/edu/unmsm/software/eapisw/controller/files/icons/icons8-edit-32.png"))); // NOI18N
        editMenu.setMnemonic('e');
        editMenu.setText("Editar");

        productEditItem.setMnemonic('t');
        productEditItem.setText("Productos");
        productEditItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productEditItemActionPerformed(evt);
            }
        });
        editMenu.add(productEditItem);

        workerEditItem.setMnemonic('p');
        workerEditItem.setText("Trabajadores");
        workerEditItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                workerEditItemActionPerformed(evt);
            }
        });
        editMenu.add(workerEditItem);

        menuBar.add(editMenu);

        consultMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/edu/unmsm/software/eapisw/controller/files/icons/icons8-consultation-30.png"))); // NOI18N
        consultMenu.setText("Consultas");

        consultClientItem.setText("Clientes");
        consultClientItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultClientItemActionPerformed(evt);
            }
        });
        consultMenu.add(consultClientItem);

        menuBar.add(consultMenu);

        configMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/edu/unmsm/software/eapisw/controller/files/icons/icons8-computer-30.png"))); // NOI18N
        configMenu.setText("Configuraciones");

        jMenuItem2.setText("Usuarios y Accesos");
        configMenu.add(jMenuItem2);

        menuBar.add(configMenu);

        helpMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/edu/unmsm/software/eapisw/controller/files/icons/icons8-help-30.png"))); // NOI18N
        helpMenu.setText("Ayuda");

        jMenuItem3.setText("Acerca de...");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        helpMenu.add(jMenuItem3);

        jMenuItem4.setText("Ayuda");
        helpMenu.add(jMenuItem4);

        menuBar.add(helpMenu);

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pe/edu/unmsm/software/eapisw/controller/files/icons/icons8-logout-rounded-left-30.png"))); // NOI18N
        btnSalir.setText("Logout");
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
        });
        menuBar.add(btnSalir);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 673, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void productEditItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productEditItemActionPerformed
        ProductoLista prod= new ProductoLista();
        desktopPane.add(prod);
        prod.toFront();
        prod.setVisible(true);
    }//GEN-LAST:event_productEditItemActionPerformed

    private void workerEditItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_workerEditItemActionPerformed
        TrabajadorLista prod= new TrabajadorLista();
        desktopPane.add(prod);
        prod.toFront();
        prod.setVisible(true);
    }//GEN-LAST:event_workerEditItemActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void consultClientItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultClientItemActionPerformed
        ClienteLista prod= new ClienteLista();
        desktopPane.add(prod);
        prod.toFront();
        prod.setVisible(true);
    }//GEN-LAST:event_consultClientItemActionPerformed

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnSalirMouseClicked

    private void ventasMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ventasMenuMouseClicked
        VentaLista pron= new VentaLista();
        desktopPane.add(pron);
        pron.toFront();
        pron.setVisible(true);
    }//GEN-LAST:event_ventasMenuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu btnSalir;
    public static javax.swing.JMenu configMenu;
    private javax.swing.JMenuItem consultClientItem;
    private javax.swing.JMenu consultMenu;
    private javax.swing.JDesktopPane desktopPane;
    public static javax.swing.JMenu editMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem productEditItem;
    private javax.swing.JMenu ventasMenu;
    private javax.swing.JMenuItem workerEditItem;
    // End of variables declaration//GEN-END:variables

}
