/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pe.edu.unmsm.software.eapisw.controller;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pe.edu.unmsm.software.eapisw.model.Trabajador;
import pe.edu.unmsm.software.eapisw.service.TrabajadorService.TrabajadorComparatorAPaterno;
import pe.edu.unmsm.software.eapisw.service.TrabajadorService.TrabajadorComparatorID;
import pe.edu.unmsm.software.eapisw.service.TrabajadorServiceImpl;

/**
 *
 * @author Purple
 */
public class TrabajadorLista extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmTrabajadorList
     */
    public TrabajadorLista() {
        initComponents();
        this.setResizable(false);
        mostrarTabla();
        
        grupo.add(radioAp);
        grupo.add(radioDoc);
        grupo.add(radioID);
        grupo.add(radioNom);
        
        radioID.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo = new javax.swing.ButtonGroup();
        btnEditar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        btnOrdenar = new javax.swing.JButton();
        radioID = new javax.swing.JRadioButton();
        radioDoc = new javax.swing.JRadioButton();
        radioNom = new javax.swing.JRadioButton();
        radioAp = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        Tabla.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(Tabla);

        btnOrdenar.setText("Ordenar");
        btnOrdenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdenarActionPerformed(evt);
            }
        });

        radioID.setText("ID");

        radioDoc.setText("Numero de Documento");

        radioNom.setText("Nombre");

        radioAp.setText("Apellido Paterno");

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setText("Arbol AVL");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1036, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnEditar)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(118, 118, 118)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(radioID)
                                    .addComponent(radioDoc))
                                .addGap(83, 83, 83)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(radioNom)
                                    .addComponent(radioAp)))
                            .addComponent(btnOrdenar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 5, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(radioID)
                            .addComponent(radioNom))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(btnOrdenar)
                                .addGap(29, 29, 29))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radioDoc)
                                .addGap(17, 17, 17))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(radioAp)
                                .addGap(17, 17, 17))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addContainerGap())))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        try {
            int seleccionado = Tabla.getSelectedRow();

            int id = Integer.parseInt(Tabla.getValueAt(seleccionado, 1).toString());
            String nombre = Tabla.getValueAt(seleccionado, 2).toString();
            String paterno = Tabla.getValueAt(seleccionado, 3).toString();
            String materno = Tabla.getValueAt(seleccionado, 4).toString();
            String tipoDoc = Tabla.getValueAt(seleccionado, 5).toString();
            String numDoc = Tabla.getValueAt(seleccionado, 6).toString();
            String direccion = Tabla.getValueAt(seleccionado, 7).toString();
            String telefono = Tabla.getValueAt(seleccionado, 8).toString();
            String email = Tabla.getValueAt(seleccionado, 9).toString();
            String login = Tabla.getValueAt(seleccionado, 10).toString();
            String acceso = Tabla.getValueAt(seleccionado, 11).toString();
            Double sueldo = Double.parseDouble(Tabla.getValueAt(seleccionado, 12).toString());

            Trabajador trabajador = new Trabajador();
            trabajador.setIdPersona(id);
            trabajador.setNombre(nombre);
            trabajador.setaPaterno(paterno);
            trabajador.setaMaterno(materno);
            trabajador.setTipoDocumento(tipoDoc);
            trabajador.setNumeroDocumento(numDoc);
            trabajador.setDireccion(direccion);
            trabajador.setTelefono(telefono);
            trabajador.setEmail(email);
            trabajador.setLogin(login);
            trabajador.setAcceso(acceso);
            trabajador.setSueldo(sueldo);

            frmTrabajadorCrear crear = new frmTrabajadorCrear();
            crear.editar(trabajador);
            //crear.setVisible(true);

        } catch (ArrayIndexOutOfBoundsException e) {
            JOptionPane.showMessageDialog(null, "Primero seleccione un trabajador.");
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnOrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenarActionPerformed
        
        TrabajadorServiceImpl trab= new TrabajadorServiceImpl();
        DefaultTableModel modelo;
        if(radioID.isSelected()){
           
            modelo= trab.ordenarArbolAVL("id");
            Tabla.setModel(modelo);
        }
        else if(radioAp.isSelected()){
            
            modelo= trab.ordenarArbolAVL("apaterno");
            Tabla.setModel(modelo);
        }
        else if(radioDoc.isSelected()){
           
            modelo= trab.ordenarArbolAVL("");
            Tabla.setModel(modelo);
        }else{
           
            modelo= trab.ordenarArbolAVL("nombre");
            Tabla.setModel(modelo);
        }
    }//GEN-LAST:event_btnOrdenarActionPerformed

    void darFormaTabla() {
        Tabla.getColumnModel().getColumn(0).setMinWidth(20);
        Tabla.getColumnModel().getColumn(1).setMinWidth(20);
        Tabla.getColumnModel().getColumn(2).setMinWidth(100);
        Tabla.getColumnModel().getColumn(3).setMinWidth(100);
        Tabla.getColumnModel().getColumn(4).setMinWidth(100);
        Tabla.getColumnModel().getColumn(5).setMinWidth(100);
        Tabla.getColumnModel().getColumn(6).setMinWidth(120);
        Tabla.getColumnModel().getColumn(7).setMinWidth(30);
        Tabla.getColumnModel().getColumn(8).setMinWidth(100);
        Tabla.getColumnModel().getColumn(9).setMinWidth(50);
        Tabla.getColumnModel().getColumn(10).setMinWidth(100);
        Tabla.getColumnModel().getColumn(11).setMinWidth(100);
        Tabla.getColumnModel().getColumn(12).setMinWidth(50);

    }

    public void mostrarTabla() {
        TrabajadorServiceImpl trabajadorService = new TrabajadorServiceImpl();
        DefaultTableModel modelo = trabajadorService.mostrarArbolAVL();
        Tabla.setModel(modelo);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnOrdenar;
    private javax.swing.ButtonGroup grupo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radioAp;
    private javax.swing.JRadioButton radioDoc;
    private javax.swing.JRadioButton radioID;
    private javax.swing.JRadioButton radioNom;
    // End of variables declaration//GEN-END:variables
}
