-- MySQL Script generated by MySQL Workbench
-- Wed Jun 19 11:53:36 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema almacenED
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema almacenED
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `almacenED`;
CREATE SCHEMA IF NOT EXISTS `almacenED` DEFAULT CHARACTER SET utf8 COLLATE utf8_lithuanian_ci ;
USE `almacenED` ;

-- -----------------------------------------------------
-- Table `almacenED`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `almacenED`.`producto` (
  `idproducto` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(10) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(255) NULL,
  `caracteristicas` VARCHAR(512) NULL,
  `stock` INT NOT NULL,
  `precio_venta` DECIMAL(7,2) NOT NULL,
  PRIMARY KEY (`idproducto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `almacenED`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `almacenED`.`persona` (
  `idpersona` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apaterno` VARCHAR(20) NOT NULL,
  `amaterno` VARCHAR(20) NOT NULL,
  `tipo_documento` VARCHAR(20) NOT NULL,
  `num_documento` VARCHAR(10) NOT NULL,
  `direccion` VARCHAR(100) NULL,
  `telefono` VARCHAR(15) NULL,
  `email` VARCHAR(25) NULL,
  PRIMARY KEY (`idpersona`),
  UNIQUE INDEX `telefono_UNIQUE` (`telefono` ASC) ,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `almacenED`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `almacenED`.`cliente` (
  `idpersona` INT NOT NULL,
  `codigo_cliente` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idpersona`),
  UNIQUE INDEX `codigo_cliente_UNIQUE` (`codigo_cliente` ASC) ,
  CONSTRAINT `fk_persona_cliente`
    FOREIGN KEY (`idpersona`)
    REFERENCES `almacenED`.`persona` (`idpersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `almacenED`.`trabajador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `almacenED`.`trabajador` (
  `idpersona` INT NOT NULL,
  `sueldo` DECIMAL(7,2) NOT NULL,
  `acceso` VARCHAR(45) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idpersona`),
  CONSTRAINT `fk_persona_trabajador`
    FOREIGN KEY (`idpersona`)
    REFERENCES `almacenED`.`persona` (`idpersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `almacenED`.`consumo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `almacenED`.`consumo` (
  `idconsumo` INT NOT NULL AUTO_INCREMENT,
  `idproducto` INT NOT NULL,
  `idtrabajador` INT NOT NULL,
  `idcliente` INT NOT NULL,
  `cantidad` DECIMAL(7,2) NOT NULL,
  `precio_venta` DECIMAL(7,2) NOT NULL,
  PRIMARY KEY (`idconsumo`),
  INDEX `fk_consumo_producto_idx` (`idproducto` ASC) ,
  INDEX `fk_consumo_trabajador_idx` (`idtrabajador` ASC) ,
  INDEX `fk_consumo_cliente_idx` (`idcliente` ASC) ,
  CONSTRAINT `fk_consumo_producto`
    FOREIGN KEY (`idproducto`)
    REFERENCES `almacenED`.`producto` (`idproducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_consumo_trabajador`
    FOREIGN KEY (`idtrabajador`)
    REFERENCES `almacenED`.`trabajador` (`idpersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_consumo_cliente`
    FOREIGN KEY (`idcliente`)
    REFERENCES `almacenED`.`cliente` (`idpersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `almacenED`.`pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `almacenED`.`pago` (
  `idpago` INT NOT NULL AUTO_INCREMENT,
  `idconsumo` INT NOT NULL,
  `tipo_comprobante` VARCHAR(20) NOT NULL,
  `num_comprobante` VARCHAR(20) NOT NULL,
  `igv` DECIMAL(4,2) NOT NULL,
  `total_pago` DECIMAL(7,2) NOT NULL,
  `fecha_emision` DATE NOT NULL,
  PRIMARY KEY (`idpago`),
  INDEX `fk_pago_reserva_idx` (`idconsumo` ASC) ,
  CONSTRAINT `fk_pago_reserva`
    FOREIGN KEY (`idconsumo`)
    REFERENCES `almacenED`.`consumo` (`idconsumo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

ALTER TABLE `almacened`.`producto` 
CHANGE COLUMN `codigo` `codigo` VARCHAR(15) NOT NULL ;




SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
